[project]
name = "projet3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "youdontknowmu", email = "youdontknowmu@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "statsmodels>=0.15.0",
]

[project.scripts]
projet3 = "projet3:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
